import {analyze,credit,liquidity,money,policies} from '../../../lib/risk';
import {getDataset,snowSQL,snowflakeConfig} from '../../../lib/snowflake';
export async function POST(request:Request){
 try{
 const {question}=await request.json() as {question?:unknown};
 if(typeof question!=='string'||!question.trim()||question.length>1000)return Response.json({error:'Enter a question of 1–1,000 characters.'},{status:400});
 const {data,mode,queryId}=await getDataset();const q=question.toLowerCase();let answer='';let refs:string[]=[];let intent='';
 const alerts=analyze(data,40);const account=q.match(/acc-\d{3}/i)?.[0]?.toUpperCase();
 if(account){const a=alerts.find(x=>x.account===account);const exists=data.accounts.some(x=>x.id===account);intent='account-investigation';answer=a?`${account} has a monitoring score of ${a.score}/100. ${a.rules.map(r=>r.detail).join(' ')} Total observed outward flow: ${money(a.amount)} across ${a.transactions.length} transactions. Confirm economic purpose, shared-device ownership, and source of funds before escalation. These signals do not establish fraud.`:exists?`${account} has no monitoring signals at the current minimum score of 40. This does not prove that its activity is legitimate.`:`${account} was not found in this dataset.`;refs=a?a.rules.map(r=>r.code):[];
 }else if(/liquid|lcr|outflow|basel/.test(q)){intent='liquidity-risk';const shock=Math.min(100,Number(q.match(/(\d+)\s*%/)?.[1]||0));const l=liquidity(data,shock);answer=`At ${shock}% outflow stress, illustrative liquidity coverage is ${l.lcr.toFixed(1)}%. HQLA: ${money(data.liquidity.hqla)}; modeled 30-day net outflows: ${money(l.net)}. ${l.shortfall>0?`HQLA shortfall against the illustrative 100% floor is ${money(l.shortfall)}.`:'No modeled shortfall against the illustrative 100% floor.'} Inflows are capped at 75% of outflows. Asset eligibility, runoff factors and jurisdiction-specific reporting are not validated.`;refs=['POL-06'];
 }else if(/credit|loan|loss|exposure|default|sector/.test(q)){intent='credit-risk';const c=credit(data);answer=`The synthetic loan portfolio has exposure of ${money(c.ead)} and modeled expected loss of ${money(c.loss)}. Exposure at 90+ days past due is ${money(c.pastDue)}. Expected loss sums EAD × PD × LGD per loan. With a 2× PD shock (capped at 100%), expected loss rises to ${money(credit(data,2).loss)}. These are scenario assumptions, not validated predictive estimates.`;refs=['POL-05'];
 }else if(/fraud|risk|suspicious|alert|circular|structur|device|signal|report|finding|aml|transaction/.test(q)){intent='fraud-triage';answer=`${alerts.length} accounts meet the review threshold of 40/100. ${alerts.slice(0,4).map(a=>`${a.account}: score ${a.score}, ${a.rules.map(r=>r.label.toLowerCase()).join(', ')}`).join('; ')}. Highest priority: ${alerts[0]?.account||'none'}. Open its evidence panel to inspect transaction IDs and policy clauses, then export a finding draft for human review. Scores measure rule severity, not probability of fraud.`;refs=[...new Set(alerts.flatMap(a=>a.rules.map(r=>r.code)))];
 }else{return Response.json({answer:'I can investigate an account ID (for example ACC-001), summarize fraud alerts, calculate credit expected loss, or model liquidity stress (for example “LCR under 20% outflow stress”). Your question is outside these governed query types.',refs:[],mode,intent:'unsupported',queryId});}
 let engine='Governed calculation';
 if(mode==='snowflake-live'&&snowflakeConfig('SNOWFLAKE_CORTEX_ENABLED')==='true'){
  try{const context=JSON.stringify({question,facts:answer,policies:policies.filter(p=>refs.includes(p.id))});const r=await snowSQL("SELECT SNOWFLAKE.CORTEX.COMPLETE('mistral-large2', CONCAT('Summarize only the provided facts. Preserve numbers and policy IDs. Do not invent regulations, guilt, or certainty. State that human review is required. Context: ', ?))",{'1':{type:'TEXT',value:context}});answer=r.data?.[0]?.[0]||answer;engine='Snowflake Cortex';}catch{engine='Governed calculation (Cortex unavailable)';}
 }
 return Response.json({answer,refs,mode,intent,queryId,engine});
 }catch{return Response.json({error:'Analysis is unavailable. Check the Snowflake connection or retry.'},{status:503});}
}

